services:
  webserver1:
    image: httpd:alpine
    container_name: webserver1
    restart: always
    ports:
      - "8081:80"
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: es
    ports:
      - "9200:80"
      
    
