services:
  webserver1:
    image: httpd:alpine
    container_name: webserver1
    restart: always
    ports:
      - "8081:80"
webserver2:
    image: httpd:alpine
    container_name: webserver2
    restart: always
    ports:
      - "8082:80"
    
