services:
  webserver1:
    image: httpd:alpine
    container_name: webserver1
    restart: always
    ports:
      - "8081:80"
  web:     
    build:
      context: .       
      dockerfile: Dockerfile
    ports:
      - "9200":80"
      
    
